set -g fish_color_autosuggestion    b8b8b8
set -g fish_color_cancel            \x2dr
set -g fish_color_command           a1b56c
set -g fish_color_comment           f7ca88
set -g fish_color_cwd               green
set -g fish_color_cwd_root          red
set -g fish_color_end               ba8baf
set -g fish_color_error             ab4642
set -g fish_color_escape            86c1b9
set -g fish_color_history_current   \x2d\x2dbold
set -g fish_color_host              normal
set -g fish_color_host_remote       yellow
set -g fish_color_match             7cafc2
set -g fish_color_normal            normal
set -g fish_color_operator          7cafc2
set -g fish_color_param             383838
set -g fish_color_quote             f7ca88
set -g fish_color_redirection       383838
set -g fish_color_search_match      bryellow\x1e\x2d\x2dbackground\x3dbrblack
set -g fish_color_selection         white\x1e\x2d\x2dbold\x1e\x2d\x2dbackground\x3dbrblack
set -g fish_color_status            red
set -g fish_color_user              brgreen
set -g fish_color_valid_path        \x2d\x2dunderline
set -g fish_greeting                Welcome\x20to\x20fish\x2c\x20the\x20friendly\x20interactive\x20shell
set -g fish_key_bindings            fish_default_key_bindings
set -g fish_pager_color_completion  normal
set -g fish_pager_color_description B3A06D\x1eyellow
set -g fish_pager_color_prefix      white\x1e\x2d\x2dbold\x1e\x2d\x2dunderline
set -g fish_pager_color_progress    brwhite\x1e\x2d\x2dbackground\x3dcyan
