set -g fish_color_autosuggestion    586e75
set -g fish_color_cancel            \x2dr
set -g fish_color_command           93a1a1
set -g fish_color_comment           586e75
set -g fish_color_cwd               green
set -g fish_color_cwd_root          red
set -g fish_color_end               268bd2
set -g fish_color_error             dc322f
set -g fish_color_escape            00a6b2
set -g fish_color_history_current   \x2d\x2dbold
set -g fish_color_host              normal
set -g fish_color_host_remote       yellow
set -g fish_color_match             \x2d\x2dbackground\x3dbrblue
set -g fish_color_normal            normal
set -g fish_color_operator          00a6b2
set -g fish_color_param             839496
set -g fish_color_quote             657b83
set -g fish_color_redirection       6c71c4
set -g fish_color_search_match      bryellow\x1e\x2d\x2dbackground\x3dblack
set -g fish_color_selection         white\x1e\x2d\x2dbold\x1e\x2d\x2dbackground\x3dbrblack
set -g fish_color_status            red
set -g fish_color_user              brgreen
set -g fish_color_valid_path        \x2d\x2dunderline
set -g fish_greeting                Welcome\x20to\x20fish\x2c\x20the\x20friendly\x20interactive\x20shell
set -g fish_key_bindings            fish_default_key_bindings
set -g fish_pager_color_completion  B3A06D
set -g fish_pager_color_description B3A06D
set -g fish_pager_color_prefix      cyan\x1e\x2d\x2dunderline
set -g fish_pager_color_progress    brwhite\x1e\x2d\x2dbackground\x3dcyan
